[package]
authors = ["Nexis Maintainers <maintainers@nexis.foundation>"]
edition = "2021"
name = "nexis-sys-tuner"
description = "The nexiscluster system tuner daemon"
version = "1.9.29"
repository = "https://github.com/nexis-network/nexis"
license = "Apache-2.0"
homepage = "https://nexis.network/"
documentation = "https://docs.rs/nexis-sys-tuner"
publish = true

[dependencies]
clap = "2.33.1"
log = "0.4.14"
libc = "0.2.108"
nexis-logger = { path = "../logger", version = "=1.9.29" }
nexis-version = { path = "../version", version = "=0.6.3" }

[target."cfg(unix)".dependencies]
unix_socket2 = "0.5.4"
users = "0.10.0"
nix = "0.23.0"
sysctl = "0.4.3"

[lib]
name = "nexis_sys_tuner"

[[bin]]
name = "nexis-sys-tuner"
path = "src/main.rs"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
