[package]
name = "nexis-config-program"
version = "1.9.29"
description = "Nexis Config program"
authors = ["Nexis Maintainers <maintainers@nexis.foundation>"]
repository = "https://github.com/nexis-network/nexis"
license = "Apache-2.0"
homepage = "https://nexis.network/"
documentation = "https://docs.rs/nexis-config-program"
edition = "2021"

[dependencies]
bincode = "1.3.3"
chrono = { version = "0.4.11", features = ["serde"] }
serde = "1.0.130"
serde_derive = "1.0.103"
nexis-program-runtime = { path = "../../program-runtime", version = "=1.9.29" }
nexis-sdk = { path = "../../sdk", version = "=1.9.29" }

[dev-dependencies]
nexis-logger = { path = "../../logger", version = "=1.9.29" }

[lib]
crate-type = ["lib"]
name = "nexis_config_program"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
