[package]
authors = ["Nexis Maintainers <maintainers@nexis.foundation>"]
edition = "2021"
name = "nexis-net-shaper"
description = "The nexiscluster network shaping tool"
version = "1.9.29"
repository = "https://github.com/nexis-network/nexis"
license = "Apache-2.0"
homepage = "https://nexis.network/"
publish = false

[dependencies]
clap = "2.33.1"
serde = "1.0.130"
serde_json = "1.0.72"
nexis-clap-utils = { path = "../clap-utils", version = "=1.9.29" }
nexis-logger = { path = "../logger", version = "=1.9.29" }
rand = "0.7.0"

[[bin]]
name = "nexis-net-shaper"
path = "src/main.rs"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
