[package]
name = "nexis-cargo-build-bpf"
version = "1.9.29"
description = "Compile a local package and all of its dependencies using the Nexis BPF SDK"
authors = ["Nexis Maintainers <maintainers@nexis.foundation>"]
repository = "https://github.com/nexis-network/nexis"
homepage = "https://nexis.network/"
license = "Apache-2.0"
edition = "2021"
publish = false

[dependencies]
bzip2 = "0.4.3"
clap = "2.33.3"
regex = "1.5.4"
cargo_metadata = "0.15.1"
nexis-sdk = { path = "..", version = "=1.9.29" }
nexis-download-utils = { path = "../../download-utils", version = "=1.9.29" }
tar = "0.4.37"

[dev-dependencies]
serial_test = "*"

[features]
program = []

[[bin]]
name = "cargo-build-bpf"
path = "src/main.rs"
