[package]
name = "nexis-ed25519-program-tests"
version = "1.9.29"
authors = ["Nexis Maintainers <maintainers@nexis.foundation>"]
repository = "https://github.com/nexis-network/nexis"
license = "Apache-2.0"
homepage = "https://nexis.network/"
edition = "2021"
publish = false

[dev-dependencies]
assert_matches = "1.5.0"
ed25519-dalek = "=1.0.1"
rand = "0.7.0"
nexis-program-test = { path = "../../program-test", version = "=1.9.29" }
nexis-sdk = { path = "../../sdk", version = "=1.9.29" }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
