[package]
authors = ["Nexis Maintainers <maintainers@nexis.network>"]
description = "Blockchain, Rebuilt for Scale"
edition = "2021"
homepage = "https://nexis.network/"
license = "Apache-2.0"
name = "proto"
publish = false
repository = "https://github.com/nexis-network/nexis"
version = "1.9.29"

[workspace]

[dependencies]
tonic-build = "0.8.0"
