[package]
authors = ["Nexis Maintainers <maintainers@nexis.foundation>"]
edition = "2021"
name = "nexis-local-cluster"
description = "Blockchain, Rebuilt for Scale"
version = "1.9.29"
repository = "https://github.com/nexis-network/nexis"
license = "Apache-2.0"
homepage = "https://nexis.network/"
documentation = "https://docs.rs/nexis-local-cluster"

[dependencies]
crossbeam-channel = "0.5"
itertools = "0.10.1"
gag = "1.0.0"
fs_extra = "1.2.0"
log = "0.4.14"
rand = "0.7.0"
rayon = "1.5.1"
nexis-config-program = { path = "../programs/config", version = "=1.9.29" }
nexis-core = { path = "../core", version = "=1.9.29" }
nexis-client = { path = "../client", version = "=1.9.29" }
nexis-download-utils = { path = "../download-utils", version = "=1.9.29" }
nexis-entry = { path = "../entry", version = "=1.9.29" }
nexis-gossip = { path = "../gossip", version = "=1.9.29" }
nexis-ledger = { path = "../ledger", version = "=1.9.29" }
nexis-logger = { path = "../logger", version = "=1.9.29" }
nexis-runtime = { path = "../runtime", version = "=1.9.29" }
nexis-sdk = { path = "../sdk", version = "=1.9.29" }
nexis-stake-program = { path = "../programs/stake", version = "=1.9.29" }
nexis-streamer = { path = "../streamer", version = "=1.9.29" }
nexis-vote-program = { path = "../programs/vote", version = "=1.9.29" }
tempfile = "3.2.0"

[dev-dependencies]
assert_matches = "1.5.0"
serial_test = "0.5.1"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[features]
default = []
multiple-db-in-thread = []
