[package]
name = "nexis-bpf-rust-error-handling"
version = "1.9.29"
description = "Nexis BPF test program written in Rust"
authors = ["Nexis Maintainers <maintainers@nexis.foundation>"]
repository = "https://github.com/nexis-network/nexis"
license = "Apache-2.0"
homepage = "https://nexis.network/"
documentation = "https://docs.rs/nexis-bpf-rust-error-handling"
edition = "2021"

[dependencies]
num-derive = "0.3"
num-traits = "0.2"
nexis-program = { path = "../../../../sdk/program", version = "=1.9.29" }
thiserror = "1.0"

[lib]
crate-type = ["cdylib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
