[package]
authors = ["Nexis Maintainers <maintainers@nexis.foundation>"]
edition = "2021"
name = "nexis-replica-node"
description = "Nexis replication node"
version = "1.9.29"
repository = "https://github.com/nexis-network/nexis"
license = "Apache-2.0"
homepage = "https://nexis.network/"
documentation = "https://docs.rs/nexis-validator"

[dependencies]
clap = "2.33.1"
crossbeam-channel = "0.5"
log = "0.4.14"
rand = "0.7.0"
nexis-clap-utils = { path = "../clap-utils", version = "=1.9.29" }
nexis-download-utils = { path = "../download-utils", version = "=1.9.29" }
nexis-genesis-utils = { path = "../genesis-utils", version = "=1.9.29" }
nexis-gossip = { path = "../gossip", version = "=1.9.29" }
nexis-ledger = { path = "../ledger", version = "=1.9.29" }
nexis-logger = { path = "../logger", version = "=1.9.29" }
nexis-net-utils = { path = "../net-utils", version = "=1.9.29" }
nexis-rpc = { path = "../rpc", version = "=1.9.29" }
nexis-replica-lib = { path = "../replica-lib", version = "=1.9.29" }
nexis-runtime = { path = "../runtime", version = "=1.9.29" }
nexis-sdk = { path = "../sdk", version = "=1.9.29" }
nexis-send-transaction-service = { path = "../send-transaction-service", version = "=1.9.29" }
nexis-streamer = { path = "../streamer", version = "=1.9.29" }
nexis-version = { path = "../version", version = "=0.6.3" }
exzo-validator = { path = "../validator", version = "=1.9.29" }

[dev-dependencies]
serial_test = "0.5.1"
nexis-core = { path = "../core", version = "=1.9.29" }
nexis-local-cluster = { path = "../local-cluster", version = "=1.9.29" }
tempfile = "3.2.0"


[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[build-dependencies]
tonic-build = "0.8.0"
