[package]
name = "nexis-bpf-loader-program"
version = "1.9.29"
description = "Nexis BPF loader"
authors = ["Nexis Maintainers <maintainers@nexis.foundation>"]
repository = "https://github.com/nexis-network/nexis"
license = "Apache-2.0"
homepage = "https://nexis.network/"
documentation = "https://docs.rs/nexis-bpf-loader-program"
edition = "2021"

[dependencies]
bincode = "1.3.3"
byteorder = "1.4.3"
log = "0.4.14"
libsecp256k1 = "0.6.0"
nexis-measure = { path = "../../measure", version = "=1.9.29" }
nexis-metrics = { path = "../../metrics", version = "=1.9.29" }
nexis-program-runtime = { path = "../../program-runtime", version = "=1.9.29" }
nexis-sdk = { path = "../../sdk", version = "=1.9.29" }
nexis_rbpf = "=0.2.24"
thiserror = "1.0"

[dev-dependencies]
rand = "0.7.3"
nexis-runtime = { path = "../../runtime", version = "=1.9.29" }

[lib]
crate-type = ["lib"]
name = "nexis_bpf_loader_program"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
