[package]
name = "nexis-bpf-rust-param-passing-dep"
version = "1.9.29"
description = "Nexis BPF program written in Rust"
authors = ["Nexis Maintainers <maintainers@nexis.foundation>"]
repository = "https://github.com/nexis-network/nexis"
license = "Apache-2.0"
homepage = "https://nexis.network/"
documentation = "https://docs.rs/nexis-bpf-rust-param-passing-dep"
edition = "2021"

[dependencies]
nexis-program = { path = "../../../../sdk/program", version = "=1.9.29" }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
