[package]
authors = ["Nexis Maintainers <maintainers@nexis.foundation>"]
edition = "2021"
name = "nexis-validator"
description = "Blockchain, Rebuilt for Scale"
version = "1.9.29"
repository = "https://github.com/nexis-network/nexis"
license = "Apache-2.0"
homepage = "https://nexis.network/"
default-run = "nexis-validator"

[dependencies]
chrono = { version = "0.4.11", features = ["serde"] }
clap = "2.33.1"
console = "0.15.0"
core_affinity = "0.5.10"
fd-lock = "3.0.1"
indicatif = "0.16.2"
jsonrpc-core = "18.0.0"
jsonrpc-core-client = { version = "18.0.0", features = ["ipc", "ws"] }
jsonrpc-derive = "18.0.0"
jsonrpc-ipc-server = "18.0.0"
jsonrpc-server-utils= "18.0.0"
log = "0.4.14"
num_cpus = "1.13.0"
rand = "0.7.0"
nexis-clap-utils = { path = "../clap-utils", version = "=1.9.29" }
nexis-cli-config = { path = "../cli-config", version = "=1.9.29" }
nexis-client = { path = "../client", version = "=1.9.29" }
nexis-core = { path = "../core", version = "=1.9.29" }
nexis-download-utils = { path = "../download-utils", version = "=1.9.29" }
nexis-entry = { path = "../entry", version = "=1.9.29" }
nexis-faucet = { path = "../faucet", version = "=1.9.29" }
nexis-genesis-utils = { path = "../genesis-utils", version = "=1.9.29" }
nexis-gossip = { path = "../gossip", version = "=1.9.29" }
nexis-ledger = { path = "../ledger", version = "=1.9.29" }
nexis-logger = { path = "../logger", version = "=1.9.29" }
nexis-metrics = { path = "../metrics", version = "=1.9.29" }
nexis-net-utils = { path = "../net-utils", version = "=1.9.29" }
nexis-perf = { path = "../perf", version = "=1.9.29" }
nexis-poh = { path = "../poh", version = "=1.9.29" }
nexis-replica-lib = { path = "../replica-lib", version = "=1.9.29" }
nexis-rpc = { path = "../rpc", version = "=1.9.29" }
nexis-runtime = { path = "../runtime", version = "=1.9.29" }
nexis-sdk = { path = "../sdk", version = "=1.9.29" }
nexis-send-transaction-service = { path = "../send-transaction-service", version = "=1.9.29" }
nexis-streamer = { path = "../streamer", version = "=1.9.29" }
nexis-test-validator = { path = "../test-validator", version = "=1.9.29" }
nexis-version = { path = "../version", version = "=0.6.3" }
nexis-vote-program = { path = "../programs/vote", version = "=1.9.29" }
symlink = "0.1.0"

evm-state = { path = "../evm-utils/evm-state" }
tempfile = "3"
[target.'cfg(not(target_env = "msvc"))'.dependencies]
jemallocator = {package = "tikv-jemallocator", version = "0.4.1", features = ["unprefixed_malloc_on_supported_platforms"]}

[target."cfg(unix)".dependencies]
libc = "0.2.108"
signal-hook = "0.3.10"
sysctl = "0.4.3"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
