[package]
name = "nexis-runtime"
version = "1.9.29"
description = "Nexis runtime"
authors = ["Nexis Maintainers <maintainers@nexis.foundation>"]
repository = "https://github.com/nexis-network/nexis"
license = "Apache-2.0"
homepage = "https://nexis.network/"
documentation = "https://docs.rs/nexis-runtime"
edition = "2021"

[dependencies]
arrayref = "0.3.6"
bincode = "1.3.3"
blake3 = "1.2.0"
bv = { version = "0.11.1", features = ["serde"] }
bytemuck = "1.7.2"
byteorder = "1.4.3"
bzip2 = "0.4.3"
dashmap = { version = "4.0.2", features = ["rayon", "raw-api"] }
crossbeam-channel = "0.5"
flate2 = "1.0.22"
fnv = "1.0.7"
index_list = "0.2.7"
itertools = "0.10.1"
lazy_static = "1.4.0"
log = "0.4.14"
memmap2 = "0.5.0"
num_cpus = "1.13.0"
num-derive = { version = "0.3" }
num-traits = { version = "0.2" }
ouroboros = "0.13.0"
rand = "0.7.0"
rayon = "1.5.1"
regex = "1.5.4"
serde = { version = "1.0.130", features = ["rc"] }
serde_derive = "1.0.103"
nexis-address-lookup-table-program = { path = "../programs/address-lookup-table", version = "=1.9.29" }
nexis-bloom = { path = "../bloom", version = "=1.9.29" }
nexis-config-program = { path = "../programs/config", version = "=1.9.29" }
nexis-compute-budget-program = { path = "../programs/compute-budget", version = "=1.9.29" }
nexis-frozen-abi = { path = "../frozen-abi", version = "=1.9.29" }
nexis-frozen-abi-macro = { path = "../frozen-abi/macro", version = "=1.9.29" }
nexis-logger = { path = "../logger", version = "=1.9.29" }
nexis-measure = { path = "../measure", version = "=1.9.29" }
nexis-metrics = { path = "../metrics", version = "=1.9.29" }
nexis-bucket-map = { path = "../bucket_map", version = "=1.9.29" }
nexis-program-runtime = { path = "../program-runtime", version = "=1.9.29" }
nexis-rayon-threadlimit = { path = "../rayon-threadlimit", version = "=1.9.29" }
nexis-sdk = { path = "../sdk", version = "=1.9.29" }
nexis-stake-program = { path = "../programs/stake", version = "=1.9.29" }
nexis-vote-program = { path = "../programs/vote", version = "=1.9.29" }
symlink = "0.1.0"
tar = "0.4.37"
tempfile = "3.2.0"
thiserror = "1.0"
walkdir = "2.3.2"
zstd = "0.9.0"

evm-state = { path = "../evm-utils/evm-state" }
evm-rpc = { path = "../evm-utils/evm-rpc" }
nexis-evm-loader-program = { path = "../evm-utils/programs/evm_loader" }
exzo-account-program = { path = "../programs/exzo-account-program" }
nexis-relying-party-program = { path = "../programs/nexis-relying-party-program" }
anyhow = "1.0.34"


[lib]
crate-type = ["lib"]
name = "nexis_runtime"

[dev-dependencies]
assert_matches = "1.5.0"
ed25519-dalek = "=1.0.1"
libsecp256k1 = "0.6.0"
rand_chacha = "0.2.2"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[build-dependencies]
rustc_version = "0.4"
