[package]
authors = ["Nexis Maintainers <maintainers@nexis.network>"]
edition = "2021"
name = "nexis-log-analyzer"
description = "The nexiscluster network analysis tool"
version = "1.9.29"
repository = "https://github.com/nexis-network/nexis"
license = "Apache-2.0"
homepage = "https://nexis.network/"
publish = false

[dependencies]
byte-unit = "4.0.13"
clap = "2.33.1"
serde = "1.0.130"
serde_json = "1.0.72"
nexis-logger = { path = "../logger", version = "=1.9.29" }
nexis-version = { path = "../version", version = "=0.6.3" }

[[bin]]
name = "nexis-log-analyzer"
path = "src/main.rs"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
