[package]
name = "nexis-compute-budget-program"
description = "Nexis Compute Budget program"
version = "1.9.29"
homepage = "https://nexis.network/"
documentation = "https://docs.rs/nexis-compute-budget-program"
repository = "https://github.com/nexis-network/nexis"
authors = ["Nexis Maintainers <maintainers@nexis.foundation>"]
license = "Apache-2.0"
edition = "2021"

[dependencies]
nexis-program-runtime = { path = "../../program-runtime", version = "=1.9.29" }
nexis-sdk = { path = "../../sdk", version = "=1.9.29" }

[lib]
crate-type = ["lib"]
name = "nexis_compute_budget_program"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
