[package]
name = "nexis-notifier"
version = "1.9.29"
description = "Nexis Notifier"
authors = ["Nexis Maintainers <maintainers@nexis.foundation>"]
repository = "https://github.com/nexis-network/nexis"
license = "Apache-2.0"
homepage = "https://nexis.network/"
documentation = "https://docs.rs/nexis-notifier"
edition = "2021"

[dependencies]
log = "0.4.14"
reqwest = { version = "0.11.6", default-features = false, features = ["blocking", "rustls-tls", "json"] }
serde_json = "1.0"

[lib]
name = "nexis_notifier"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
