[package]
name = "nexis-sleep-program"
version = "1.5.14"
description = "Nexis Noop program"
authors = ["Nexis Maintainers <maintainers@nexis.foundation>"]
repository = "https://github.com/nexis-network/nexis"
license = "Apache-2.0"
homepage = "https://nexis.network/"
edition = "2018"

[dependencies]
log = "0.4.11"
nexis-logger = { path = "../../logger", version = "1.9.13" }
nexis-sdk = { path = "../../sdk", version = "1.9.13" }
nexis-program-runtime = { path = "../../program-runtime", version = "1.9.13" }
byteorder = "1.4.3"

[lib]
crate-type = ["lib", "cdylib"]
name = "nexis_sleep_program"


[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
