[package]
name = "nexis-stake-accounts"
description = "Blockchain, Rebuilt for Scale"
authors = ["Nexis Maintainers <maintainers@nexis.foundation>"]
edition = "2021"
version = "1.9.29"
repository = "https://github.com/nexis-network/nexis"
license = "Apache-2.0"
homepage = "https://nexis.network/"
documentation = "https://docs.rs/nexis-stake-accounts"

[dependencies]
clap = "2.33.1"
nexis-clap-utils = { path = "../clap-utils", version = "=1.9.29" }
nexis-cli-config = { path = "../cli-config", version = "=1.9.29" }
nexis-client = { path = "../client", version = "=1.9.29" }
nexis-remote-wallet = { path = "../remote-wallet", version = "=1.9.29" }
nexis-sdk = { path = "../sdk", version = "=1.9.29" }
nexis-stake-program = { path = "../programs/stake", version = "=1.9.29" }

[dev-dependencies]
nexis-runtime = { path = "../runtime", version = "=1.9.29" }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
