[package]
name = "nexis-tokens"
description = "Blockchain, Rebuilt for Scale"
authors = ["Nexis Maintainers <maintainers@nexis.foundation>"]
edition = "2018"
version = "1.9.29"
repository = "https://github.com/nexis-network/nexis"
license = "Apache-2.0"
homepage = "https://nexis.network/"
documentation = "https://docs.rs/nexis-tokens"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
clap = "2.33.0"
console = "0.11.3"
csv = "1.1.3"
ctrlc = { version = "3.1.5", features = ["termination"] }
dirs-next = "2.0.0"
indexmap = "1.5.1"
indicatif = "0.15.0"
pickledb = { version = "0.5.1", features = ["yaml"] }
serde = { version = "1.0", features = ["derive"] }
nexis-account-decompiler = { path = "../account-decompiler", version = "=1.9.29" }
nexis-clap-utils = { path = "../clap-utils", version = "=1.9.29" }
nexis-cli-config = { path = "../cli-config", version = "=1.9.29" }
nexis-client = { path = "../client", version = "=1.9.29" }
nexis-remote-wallet = { path = "../remote-wallet", version = "=1.9.29" }
nexis-runtime = { path = "../runtime", version = "=1.9.29" }
nexis-sdk = { path = "../sdk", version = "=1.9.29" }
nexis-stake-program = { path = "../programs/stake", version = "=1.9.29" }
nexis-transaction-status = { path = "../transaction-status", version = "=1.9.29" }
nexis-version = { path = "../version", version = "=0.6.3" }
spl-associated-token-account-v1-0 = { package = "spl-associated-token-account", version = "=1.0.3" }
spl-token-v2-0 = { package = "spl-token", version = "=3.2.0", features = ["no-entrypoint"] }
tempfile = "3.1.0"
thiserror = "1.0"

[dev-dependencies]
bincode = "1.3.1"
nexis-core = { path = "../core", version = "=1.9.29" }
nexis-logger = { path = "../logger", version = "=1.9.29" }
nexis-streamer = { path = "../streamer", version = "=1.9.29" }
nexis-test-validator = { path = "../test-validator", version = "=1.9.29" }
