[package]
name = "rbpf-cli"
version = "1.9.29"
description = "CLI to test and analyze eBPF programs"
authors = ["Nexis Maintainers <maintainers@nexis.foundation>"]
repository = "https://github.com/nexis-labs/rbpf"
homepage = "https://nexis.network/"
keywords = ["BPF", "eBPF", "interpreter", "JIT"]
edition = "2021"
publish = false

[dependencies]
clap = { version = "3.0.0", features=["cargo"] }
serde = "1.0.130"
serde_json = "1.0.72"
nexis-bpf-loader-program = { path = "../programs/bpf_loader", version = "=1.9.29" }
nexis-logger = { path = "../logger", version = "=1.9.29" }
nexis-program-runtime = { path = "../program-runtime", version = "=1.9.29" }
nexis-sdk = { path = "../sdk", version = "=1.9.29" }
nexis_rbpf = "=0.2.24"
time = "0.3.5"
