[package]
name = "nexis-storage-proto"
version = "1.9.29"
description = "Nexis Storage Protobuf Definitions"
authors = ["Nexis Maintainers <maintainers@nexis.network>"]
repository = "https://github.com/nexis-network/nexis"
license = "Apache-2.0"
homepage = "https://nexis.network/"
documentation = "https://docs.rs/nexis-storage-proto"
edition = "2021"

[dependencies]
bincode = "1.3.3"
bs58 = "0.4.0"
prost = "0.11.0"
serde = "1.0.130"
nexis-account-decompiler = { path = "../account-decompiler", version = "=1.9.29" }
nexis-sdk = { path = "../sdk", version = "=1.9.29" }
nexis-transaction-status = { path = "../transaction-status", version = "=1.9.29" }

rlp = "0.5.0"
evm-state = { path = "../evm-utils/evm-state" }
[dev-dependencies]
enum-iterator = "0.7.0"

[lib]
crate-type = ["lib"]
name = "nexis_storage_proto"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[build-dependencies]
tonic-build = "0.8.0"
