[package]
authors = ["Nexis Maintainers <maintainers@nexis.foundation>"]
edition = "2018"
name = "nexis-stake-monitor"
description = "Blockchain, Rebuilt for Scale"
version = "1.6.14"
repository = "https://github.com/nexis-network/nexis"
license = "Apache-2.0"
homepage = "https://nexis.network/"
documentation = "https://docs.rs/nexis-stake-monitor"

[dependencies]
clap = "2.33.1"
console = "0.11.3"
log = "0.4.11"
serde = "1.0.122"
serde_yaml = "0.8.13"
nexis-clap-utils = { path = "../clap-utils", version = "=1.9.29" }
nexis-cli-config = { path = "../cli-config", version = "=1.9.29" }
nexis-client = { path = "../client", version = "=1.9.29" }
nexis-logger = { path = "../logger", version = "=1.9.29" }
nexis-metrics = { path = "../metrics", version = "=1.9.29" }
nexis-sdk = { path = "../sdk", version = "=1.9.29" }
nexis-stake-program = { path = "../programs/stake", version = "=1.9.29" }
nexis-transaction-status = { path = "../transaction-status", version = "=1.9.29" }
nexis-version = { path = "../version", version = "=0.6.3" }

[dev-dependencies]
serial_test = "0.4.0"
nexis-local-cluster = { path = "../local-cluster", version = "=1.9.29" }
nexis-core = { path = "../core", version = "=1.9.29" }
tempfile = "3.1.0"

[[bin]]
name = "nexis-stake-monitor"
path = "src/main.rs"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
