[package]
name = "nexis-rayon-threadlimit"
version = "1.9.29"
description = "nexis-rayon-threadlimit"
homepage = "https://nexis.network/"
documentation = "https://docs.rs/nexis-rayon-threadlimit"
readme = "../README.md"
repository = "https://github.com/nexis-network/nexis"
authors = ["Nexis Maintainers <maintainers@nexis.foundation>"]
license = "Apache-2.0"
edition = "2021"

[dependencies]
num_cpus = "1.13.0"
lazy_static = "1.4.0"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
