[package]
authors = ["Nexis Maintainers <maintainers@nexis.foundation>"]
description = "I will find you and I will stake you"
edition = "2018"
homepage = "https://nexis.network/"
documentation = "https://docs.rs/"
license = "Apache-2.0"
name = "nexis-stake-o-matic"
repository = "https://github.com/nexis-labs/stake-o-matic"
version = "1.6.14"

[dependencies]
clap = "2.33.0"
log = "0.4.11"
reqwest = { version = "0.11.10", default-features = false, features = ["blocking", "rustls-tls", "json"] }
semver = "0.9.0"
serde = { version = "1.0.122", features = ["derive"] }
serde_json = "1.0.62"
serde_yaml = "0.8.13"
nexis-clap-utils = { path = "../clap-utils", version = "=1.9.29" }
nexis-client = { path = "../client", version = "=1.9.29" }
nexis-cli-config = { path = "../cli-config", version = "=1.9.29" }
nexis-cli-output = { path = "../cli-output", version = "=1.9.29" }
nexis-logger = { path = "../logger", version = "=1.9.29" }
nexis-metrics = { path = "../metrics", version = "=1.9.29" }
nexis-notifier = { path = "../notifier", version = "=1.9.29" }
nexis-sdk = { path = "../sdk", version = "=1.9.29" }
nexis-stake-program = { path = "../programs/stake", version = "=1.9.29" }
nexis-transaction-status = { path = "../transaction-status", version = "=1.9.29" }
thiserror = "1.0.21"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
