[package]
name = "nexis-cargo-test-bpf"
version = "1.9.29"
description = "Execute all unit and integration tests after building with the Nexis BPF SDK"
authors = ["Nexis Maintainers <maintainers@nexis.foundation>"]
repository = "https://github.com/nexis-network/nexis"
homepage = "https://nexis.network/"
license = "Apache-2.0"
edition = "2021"
publish = false

[dependencies]
clap = "2.33.3"
cargo_metadata = "0.15.1"

[[bin]]
name = "cargo-test-bpf"
path = "src/main.rs"
