[package]
name = "nexis-frozen-abi-macro"
version = "1.9.29"
description = "Nexis Frozen ABI Macro"
authors = ["Nexis Maintainers <maintainers@nexis.foundation>"]
repository = "https://github.com/nexis-network/nexis"
homepage = "https://nexis.network/"
documentation = "https://docs.rs/nexis-frozen-abi-macro"
license = "Apache-2.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "1.0", features = ["full", "extra-traits"] }

[build-dependencies]
rustc_version = "0.4"
