[package]
name = "nexis-upload-perf"
version = "1.9.29"
description = "Metrics Upload Utility"
authors = ["Nexis Maintainers <maintainers@nexis.foundation>"]
repository = "https://github.com/nexis-network/nexis"
license = "Apache-2.0"
edition = "2021"
homepage = "https://nexis.network/"
publish = false

[dependencies]
serde_json = "1.0.72"
nexis-metrics = { path = "../metrics", version = "=1.9.29" }

[[bin]]
name = "nexis-upload-perf"
path = "src/upload-perf.rs"


[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
