[package]
name = "nexis-bpf-rust-simulation"
version = "1.9.29"
description = "Nexis BPF Program Simulation Differences"
authors = ["Nexis Maintainers <maintainers@nexis.foundation>"]
repository = "https://github.com/nexis-network/nexis"
license = "Apache-2.0"
homepage = "https://nexis.network/"
documentation = "https://docs.rs/nexis-bpf-rust-simulation"
edition = "2021"

[features]
test-bpf = []

[dependencies]
nexis-program = { path = "../../../../sdk/program", version = "=1.9.29" }

[dev-dependencies]
nexis-logger = { path = "../../../../logger", version = "=1.9.29" }
nexis-program-test = { path = "../../../../program-test", version = "=1.9.29" }
nexis-sdk = { path = "../../../../sdk", version = "=1.9.29" }
nexis-validator = { path = "../../../../validator", version = "=1.9.29" }

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
