[package]
name = "nexis-measure"
description = "Blockchain, Rebuilt for Scale"
version = "1.9.29"
homepage = "https://nexis.network/"
documentation = "https://docs.rs/nexis-measure"
readme = "../README.md"
repository = "https://github.com/nexis-network/nexis"
authors = ["Nexis Maintainers <maintainers@nexis.foundation>"]
license = "Apache-2.0"
edition = "2021"

[dependencies]
log = "0.4.14"
nexis-sdk = { path = "../sdk", version = "=1.9.29" }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
