[package]
name = "nexis-bpf-rust-dep-crate"
version = "1.9.29"
description = "Nexis BPF test program written in Rust"
authors = ["Nexis Maintainers <maintainers@nexis.foundation>"]
repository = "https://github.com/nexis-network/nexis"
license = "Apache-2.0"
homepage = "https://nexis.network/"
documentation = "https://docs.rs/nexis-bpf-rust-dep-crate"
edition = "2021"

[dependencies]
byteorder = { version = "1", default-features = false }
nexis-program = { path = "../../../../sdk/program", version = "=1.9.29" }

[lib]
crate-type = ["cdylib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
