[package]
authors = ["Nexis Maintainers <maintainers@nexis.foundation>"]
edition = "2021"
name = "nexis-store-tool"
description = "Tool to inspect append vecs"
version = "1.9.29"
repository = "https://github.com/nexis-network/nexis"
license = "Apache-2.0"
homepage = "https://nexis.network/"
publish = false

[dependencies]
log = { version = "0.4.14" }
nexis-logger = { path = "../../logger", version = "=1.9.29" }
nexis-version = { path = "../../version", version = "=0.6.3" }
nexis-runtime = { path = "..", version = "=1.9.29" }
clap = "2.33.1"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
