[package]
name = "nexis-metrics"
version = "1.9.29"
description = "Nexis Metrics"
authors = ["Nexis Maintainers <maintainers@nexis.foundation>"]
repository = "https://github.com/nexis-network/nexis"
license = "Apache-2.0"
homepage = "https://nexis.network/"
documentation = "https://docs.rs/nexis-metrics"
edition = "2021"

[dependencies]
env_logger = "0.9.0"
gethostname = "0.2.1"
lazy_static = "1.4.0"
log = "0.4.14"
reqwest = { version = "0.11.6", default-features = false, features = ["blocking", "rustls-tls", "json"] }
nexis-sdk = { path = "../sdk", version = "=1.9.29" }

[dev-dependencies]
rand = "0.7.0"
serial_test = "0.5.1"

[lib]
name = "nexis_metrics"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
